title: Black15801577901-Blog
description: "I'm a passionate artist who loves to draw and create. Yes, I code so much that I hardly have time to draw."
author:
  name: "Black15801577901"
  email: "blackbeard1251@outlook.com"
  url: "blackbeard.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Black15801577901"
year : "2023"

